apiVersion: apps/v1
kind: Deployment
metadata:
  name: BankApp-Deployment
  namespace: BankApp-namespace
  labels:
     app: bankapp-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bankapp-deploy
  template:
    metadata:
      labels:
        app: bankapp-deploy
    spec:
      containers:
      - name: BankApp
        image: priti17/bankapp_eks:v1

        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
