apiVersion: v1
kind: Service
metadata:
  name: BankApp-Service
  namespace: BankApp-namespace
  labels:
    app: bankapp
spec:
  selector:
    app: bankapp-deploy
  ports:
   - protocol: TCP
     port: 8080
     targetPort: 8080
